version: '2'
services:
  s3:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./s3/src/client:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend

  backend:
    build: backend
    ports:
      - "8080:3000"
    volumes:
      - ./backend/api:/opt/mianio/api
      - ./backend/run.sh:/opt/mianio/run.sh
    command: "/opt/mianio/run.sh"
